### ISSUE TITLE
Maintenance/Feature: Add ability to set up number of browsers in window

### ISSUE THREAD

**Issue by qwertyuiopzxcvbnmlkjhgfdsa1** [sonnyp/Junction#106]
User should be ale to change, set, how many browsers will be visible in window opened after click on URL.

Basic is solved here:
https://github.com/sonnyp/Junction/pull/103

Ideally it should be in settings window

**Comment by sonnyp** [comment]
It's better to solve the root issue than add a setting. https://github.com/sonnyp/Junction/issues/81

The root issue is that the UI doesn't scale well to many options. I have a WIP branch to solve that by using a grid.
