### ISSUE TITLE
Feature: Add ability to open URL in private window

### ISSUE THREAD

**Issue by qwertyuiopzxcvbnmlkjhgfdsa1** [sonnyp/Junction#107]
Add ability to open URL in private window. Depends on https://github.com/sonnyp/Junction/issues/105

How it could be implemented:
After right click on browser in window, where user can choose browser, popup with "Open in private window" should be displayed over this browser

or

Save rule for opening URL from given application always in private mode.

**Comment by sonnyp** [comment]
> After right click on browser in window, where user can choose browser, popup with "Open in private window" should be displayed over this browser

That's already implemented by listing desktop actions.

https://github.com/sonnyp/Junction/blob/main/data/screenshot-desktop-actions.png

**Comment by sonnyp** [comment]
As for

> Save rule for opening URL from given application always in private mode.

See https://github.com/sonnyp/Junction/issues/5

**Comment by spi43984** [comment]
Am on version 1.7 on Ubuntu - son't see any right click menu.

**Comment by spi43984** [comment]
My .desktop files are missing an %U parameter under actions. If I add one I do see the right click menu.

Ex. for a chromium snap install. I copied the provided .desktop file into ~/.local/share/applications and searched for the line Actions= which looks like `Actions=new-window;Incognito;TempProfile;`. That means there are three action sections. I am only interested in the incognito one which starts with `[Desktop Action Incognito]`.

There is an exec line in that section which looks like `Exec=env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/chromium_chromium.desktop /snap/bin/chromium --incognito`.

I added a %U at the end, the line looks now like `Exec=env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/chromium_chromium.desktop /snap/bin/chromium --incognito %U`. Saving that file and running `update-desktop-database ~/.local/share/applications` afterwards does the trick - I do see a right click menu now.

**Comment by spi43984** [comment]
> Please report the issue to the snap maintainer

It's not only about the snap packages, also the apt/deb ones (Ubuntu/Debian) have the same issue.
