### ISSUE TITLE
Draft: Feature: Open URL in docker

### ISSUE THREAD

**Issue by qwertyuiopzxcvbnmlkjhgfdsa1** [sonnyp/Junction#108]
Add ability to open URL in docker.
TODO: Add example, how such URL should look like.

What is scope of this feature:
Redirect URL to docker, URL will then open in classic browser.
![image](https://user-images.githubusercontent.com/92012346/216533517-9f3b9832-77e6-4adc-846b-78208bf4e94d.png)

What is NOT scope:
Set up docker
Choose the right docker image

**Comment by sonnyp** [comment]
You can make your own handlers, see "Custom scripts" in the README
