### ISSUE TITLE
NOT an issue: more media coverage

### ISSUE THREAD

**Issue by Whyglobaleyes** [sonnyp/Junction#110]
FAO developer(s),

Hello. I'm sure you know this already but if not ... Junction was covered on page 86 of the current edition (299) of [linuxformat](https://www.linuxformat.com/) magazine. 

Just about to install it cos it looks perfect for my setup, workflows and niggly irritation.

Thanks in advance for a great idea.

bw

**Comment by sonnyp** [comment]
Well no, I didn't know because FLOSS medias never get in touch with developers. It's like we don't exist and open source software falls from the sky.

Thanks for sharing!

**Comment by sonnyp** [comment]
Could you share a picture of the article?

**Comment by Whyglobaleyes** [comment]
Mr Piers Sir,

The email with photo's bounced back as file size too big - do you have a 
direct email I can use please?

Kind regards,
*Dr Atul Kumar-Beurg
* GMC 4262578
+44 20 8434 7028 <tel:+442084347028>
*www.CloudHealthUK.com <www.CloudHealthUK.com>
*
*******************************************************************************
Communication by email is considered insecure for the purposes of
privileged,
medical in confidence information and is only permitted by explicit prior
agreement.
This email is confidential and may contain privileged information. If
you are
not the intended recipient then please inform the sender that you have
received the message in error before deleting it. Please do not
disclose, copy
or distribute information in this e-mail. Disclosure, copying or
distribution of
this email may be unlawful.
*******************************************************************************

**Comment by sonnyp** [comment]
my github username minus p @fastmail.net
