### ISSUE TITLE
Junction failing to start due to Gio.js error

### ISSUE THREAD

**Issue by JoshMock** [sonnyp/Junction#115]
Forking from https://github.com/sonnyp/Junction/issues/45#issuecomment-1542385906

Junction has stopped working for me, sometime within the last few days. Running `re.sonny.Junction` from the command line I get the following:

```
(re.sonny.Junction:21250): Gjs-WARNING **: 10:04:09.835: JS ERROR: TypeError: source is null
_init@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:750:1
@resource:///re/sonny/Junction/common.js:3:25
@file:///usr/bin/re.sonny.Junction:32:6
```

It never actually seems to launch the window, but the process doesn't exit either.

I run my Arch updates about once a day. Here's a dump of everything pacman upgraded in the past ~10 days, excluding obviously unrelated stuff like Python and Haskell packages, assorted CLI tools, Docker stuff, etc: [pacdump.txt](https://github.com/sonnyp/Junction/files/11443884/pacdump.txt)

You mentioned a possibly corrupted package, or not rebooting after an update, neither of which appears to be the case. I did a full uninstall of Junction, cleaned my pacman and AUR cache, deleted orphaned packages, then reinstalled Junction, which prompted a fresh reinstall of the following packages:

- `js102-102.10.0-1`
- `libportal-0.6-1`
- `appstream-glib-0.8.2-2`
- `blueprint-compiler-0.6.0-2`
- `gjs-2:1.76.0-1`
- `libportal-gtk4-0.6-1`

This also did not help.

I also tried downgrading the following, and then re-upgraded after it didn't help:

- `xdg-desktop-portal-gnome`
- `gnome-desktop`
- `gnome-desktop-4`

I'm running:

- Junction `v1.6-2` via AUR
- Arch Linux `6.3.1-arch1-1`
- i3 `4.22 (2023-01-02)`
- gjs `1.76.0`
- gtk4 `4.10.3-1`
- glib2 `2.76.2-1`
- gnome-desktop `44.0-1`
- xdg-desktop-portal-gnome `44.1-2`
- libadwaita `1.3.2-1`

Let me know if there are any other debug steps I can take to help clarify the issue. I love Junction and am happy to get my hands dirty. :black_heart:

**Comment by sonnyp** [comment]
I'm not doing support for random Arch issues sorry, you'll have to figure it out for yourself.

You're in luck, someone already shared how to fix the issue https://aur.archlinux.org/packages/junction

Please check `aur` comments before reaching out to maintainers - specially when they don't distribute the aur package.

**Comment by antecrescent** [comment]
I hope it's okay to necro-bump this issue, but I believe this is a bug beyond "some random arch issue".
The XDG Base Directory Specification [states](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables):
>  If $XDG_DATA_DIRS is either not set or empty, a value equal to /usr/local/share/:/usr/share/ should be used. 

...but `src/bin.js` lacks these entries. I can submit a PR to fix this, if you want.
