### ISSUE TITLE
Feature Request: Copy Link

### ISSUE THREAD

**Issue by soo-shan** [sonnyp/Junction#120]
Thanks for this wonderful application. 
Can you pls add an icon to copy link directly to clipboard.

My use case is:
I use [webapp manager](https://github.com/linuxmint/webapp-manager) and the web apps doesn't show up in the junction app selector window. I know of the the copy option available when selecting the hamburger menu but wanted to avoid more clicks. :)

**Comment by sonnyp** [comment]
There is a keyboard shortcut. `Ctrl+C`

**Comment by rokejulianlockhart** [comment]
@sonnyp, so what if I have a touchscreen device?

**Comment by sonnyp** [comment]
If you had, you would tap the entry and "Select All".

**Comment by sonnyp** [comment]
This feature request sounds like it's trying to solve the wrong problem.

> I use [webapp manager](https://github.com/linuxmint/webapp-manager) and the web apps doesn't show up in the junction app selector window.

Why not? Report an issue to them.

https://github.com/sonnyp/Junction#tips-and-tricks

**Comment by sonnyp** [comment]
After looking at what webapp manager does, I think this is the proper solution https://github.com/sonnyp/Junction/issues/66

So you wouldn't even need to select the application.

**Comment by soo-shan** [comment]
> There is a keyboard shortcut. `Ctrl+C`

Yes, thanks for this but sometimes we dont feel like using keyboard. :) 





> This feature request sounds like it's trying to solve the wrong problem.
> 
> > I use [webapp manager](https://github.com/linuxmint/webapp-manager) and the web apps doesn't show up in the junction app selector window.
> 
> Why not? Report an issue to them.
> 
> https://github.com/sonnyp/Junction#tips-and-tricks

Actually webapps created using webapp manger does appear in gnome search or in Applications but not in the list that Junction shows. May be something can be done in Junction to make them visible ?

 

> After looking at what webapp manager does, I think this is the proper solution #66
> 
> So you wouldn't even need to select the application if you didn't want to.

yes, this looks promising. but looks like some background work is required for this.

**Comment by sonnyp** [comment]
> May be something can be done in Junction to make them visible ?

Report the issue to them and see if they are interested in advertising http support in the desktop files. Otherwise, Junction won't / cannot detect them as options.
