### ISSUE TITLE
Vertical list (rather than current horizontal).

### ISSUE THREAD

**Issue by rokejulianlockhart** [sonnyp/Junction#122]
With enough apps, a horizontal list will become annoying. It already is for me for apps that have long names. Please allow the user to allow (in 
Junction's [primary interface](https://github.com/sonnyp/Junction/assets/42837531/3546dd8d-e795-4a70-b753-3830b25f9a1c)) all subsequent Junction pop-ups to be vertically displayed.

**Comment by sonnyp** [comment]
https://floss.social/@sonny/109729296199866051

**Comment by rokejulianlockhart** [comment]
@sonnyp, https://mastodon.world/@hemish/109729330412792857 demonstrates that there *is* desire for this. Additionally, the rationale stated in https://floss.social/@sonny/109729296199866051 remains. I truly don't see why this is not worth implementing.
