### ISSUE TITLE
Junction doesn't remember it's previous window size

### ISSUE THREAD

**Issue by VictorVow** [sonnyp/Junction#129]
I expand Junction's window size a bit because I have 8 browsers I want to switch between. This window sizing isn't remembered though, and resets whenever Junction opens again.

**Comment by sonnyp** [comment]
It's intended.

Why do you resize the window? FYI, You can scroll or navigate with arrow keys / tab.

**Comment by Victor239** [comment]
I prefer to see all the options - there's no benefit for me to have a small window when I could instead get all the information at once. I also use a mouse instead of arrow keys to navigate as I use the middle-mouse button to open multiple browsers at once.

**Comment by Victor239** [comment]
Ah makes sense, I don't use Junction for image files so I hadn't come across that.

Good ideas. Another alternative solution is perhaps a toggle in the hamburger menu to enable/disable persisting window size.

**Comment by elektronik2k5** [comment]
How about defaulting to showing all available app icons, up to 80% of display dimensions? This way we can accommodate displays of different sizes, as well as different lengths of associated app lists to launch. No need to save or remember anything.

**Comment by nekohayo** [comment]
> Ideally, we would show multiple rows (possibly 2 max) when there is enough space, but I'm not sure if that's possible. I need to dig.

Unless something fundamentally changed in the Wayland era in that respect, it should be fairly easy to get the screen's resolution from GDK/GTK: https://docs.gtk.org/gdk4/class.Monitor.html

From there, knowing the available screen space, you could auto-size the window to avoid scrolling (without needing to remember arbitrary sizes set by the user which may indeed not fit the amount of space needed at the time for a particular URL type) before showing it.
