### ISSUE TITLE
Please don't change default applications without asking the user

### ISSUE THREAD

**Issue by wisp3rwind** [sonnyp/Junction#14]
On opening the welcome window, Junction sets itself as the default handler for URLs. I think messing with the system configuration like this is entirely inappropriate. Please reconsider this behaviour. An alternative might be to add a button to this window to trigger this.

In my case, I just discovered Junction through the [This week in GNOME](https://thisweek.gnome.org/posts/2021/10/twig-15/) blog. It seemed useful, so I installed it and gave it a go. Looking for a preferences window (since Junction renders huge icons on my system, rendering it inconvenient to unusable depending on the number of handlers for a filetype), I opened the Junction application itself (without opening a document). Consequently, it installed itself as the default url handler. I particularly _don't_ want to use Junction for URLs, the usecase would be exclusively PDFs.

**Comment by sonnyp** [comment]
Fixed in 1.2.0
