### ISSUE TITLE
Browser name label option

### ISSUE THREAD

**Issue by LordShedy** [sonnyp/Junction#18]
Hi,

this app is such a beautiful extension to the system, loving it!

I am using several desktop files for differently configured firefox instances. When using Junction I cannot differentiate among the Firefox icons because I am not using different icons for the desktop files. I think it would be neat to have an option to enable some sort of label (for example Name from the desktop file).

![Screenshot from 2021-10-25 19-38-57](https://user-images.githubusercontent.com/1622827/138744528-375136cd-13a8-4194-9454-d752b57d8665.png)
![Screenshot-20211025194014-1920x1080](https://user-images.githubusercontent.com/1622827/138744550-e2fa6a63-01e1-4402-9ece-2c820a8e3cde.png)

**Comment by rafaelmardojai** [comment]
> If your profiles are named Chromium Work - Chromium School - ... you still won't be able to differentiate because there isn't enough space for the text

Probably not ideal, but what about ellipsize in the middle?

**Comment by sonnyp** [comment]
It looks strange.

![Screenshot from 2021-11-10 00-23-42](https://user-images.githubusercontent.com/19673/141021602-e2b4c792-8db5-4ef8-ba2e-24f362cfd2a4.png)

**Comment by sonnyp** [comment]
GNOME Shell application switcher suffers from the same problem

![image](https://user-images.githubusercontent.com/19673/141022129-29fbb7c7-4ce5-40cd-b4e7-3b4a065219aa.png)

If someone is motivated they can try to achieve something similar to what the GNOME Shell app grid does.

**Comment by sonnyp** [comment]
Fixed in 1.2.0

**Comment by Zzombiee2361** [comment]
Can't you just make the text multi line? Although doing that probably will make the text harder to ellipsis
