### ISSUE TITLE
Junction doesn't appear in default apps

### ISSUE THREAD

**Issue by sonnyp** [sonnyp/Junction#27]
On first install/launch - Junction isn't an option in default apps after pressing `Set Junction as default for Web` even thought it has been set as default.

After closing `gnome-control-center` and pressing on `Set Junction as default for Web` again Junction appeared

The problem appears to occur only when installed with system flathub - not user.

Steps to reproduce

* Setup a Fedora workstation 35 box
* Install flathub https://flatpak.org/setup/Fedora/
* `flatpak install re.sonny.Junction`
* flatpak start re.sonny.Junction
* Click on `Set Junction as default for Web`

cc @BrainBlasted who originally reported the issue

**Comment by sonnyp** [comment]
An other way to reproduce this although it's probably a different issue

* `flatpak remove re.sonny.Junction`
* `gnome-control-center default-apps`
* `flatpak install re.sonny.Junction`
* `flatpak run re.sonny.Junction`
* Click `Set Junction as default for Web`

**Comment by sonnyp** [comment]
Junction 1.3.0 doesn't open the gnome-control-center anymore.

It solves this and the fact that Junction wouldn't be listed in the options if the gnome-control-center was already open before Junction is installed.

**Comment by BrainBlasted** [comment]
I'm still not getting Junction listed as an available app in Settings. The button to set it as the default for web also does not seem to work.

**Comment by sonnyp** [comment]
@BrainBlasted with `1.3.0` ?

Can you run Junction in the terminal and see if you get anything useful

```
flatpak run re.sonny.Junction
```

A copy paste of `System Information` in the about dialog would be helpful too.
