### ISSUE TITLE
Host Chromium won't show in Junction flatpak

### ISSUE THREAD

**Issue by sonnyp** [sonnyp/Junction#3]
When running Junction as a flatpak, Chromium is listed if it's installed as a flatpak but not if it's installed on the host.

* Fedora 34/35
* flatpak 1.10, 1.11, 1.12.2
* chromium rpm 93.0.4577.63

The problem doesn't appear to be related to `Exec` or `TryExec`.

**Comment by Dannnington** [comment]
This is also reproducible with Firefox, in which it will only be listed if it's installed as a Flatpak. If installed on the host, it won't appear in Junction's selection menu.

System:
- Arch (rolling)
- flatpak 1.12.2

Browsers:
- Firefox Developer Edition (pacman/arch repos) 94.0b7-1
- Firefox (pacman/arch repos) 93.0-1

**Comment by sonnyp** [comment]
Do you have Firefox / Firefox Developer Edition installed as flatpaks as well?

Junction de-duplicates apps if they have the same id - that would be the cause of your issue.

**Comment by sonnyp** [comment]
Fixed in Junction 1.1.0 - should be available on flathub shortly.
