### ISSUE TITLE
Center Junction window under cursor

### ISSUE THREAD

**Issue by chase9** [sonnyp/Junction#35]
There is an application for Mac called bumpr which provides much of the same functionality. They default to placing the window under your cursor, which I believe to be the best UI for an application like this.

**Comment by sonnyp** [comment]
That's not reasonably doable under Wayland.

**Comment by sonnyp** [comment]
https://wayland-book.com/xdg-shell-in-depth/interactive.html
https://gitlab.gnome.org/GNOME/mutter/-/issues/316

Positioning a window is possible but there is no way to retrieve the cursor coordinates.

https://wayland-book.com/seat/pointer.html

**Comment by dac73** [comment]
@sonnyp is it possible at least to get it centered (via config). Currently, I just forced center all windows via gnome-tweaks, but would like to do it just for Junction.

**Comment by sonnyp** [comment]
> There is this org.gnome.mutter center-new-windows dconf setting as a half-solution.

How is that a solution to centering Junction only?

It's already documented in the README.md :+1: 

> Although it's interesting that Ulauncher somehow does it.

It's not a wayland app

https://github.com/Ulauncher/Ulauncher/blob/dev/ulauncher.service

`GDK_BACKEND=x11`
