### ISSUE TITLE
Firefox snap not listed as an option

### ISSUE THREAD

**Issue by GlitchCat** [sonnyp/Junction#50]
The Firefox browser, installed as a snap package, is not listed when opening a link and having set Junction as the default browser (using the readme)

Chrome, Brave and GNOME Web (org.gnome.Epiphany) are all listed. 
Here chrome and brave are both just installed via APT and GNOME Web via flatpak.

If I install Firefox as a flatpak package it is listed, not sure if its a problem with the way snap does things or with junction though.

System info:
- Junction 1.3.0
- Firefox 95.0.2-1 (snap package)
- Ubuntu 21.10 x86_64

Also, thanks for junction! I use it a lot and it solves all my workflow problems with having multiple programs (mainly using multiple browsers as the issue)

**Comment by GlitchCat** [comment]
Hey it works at my end! 
Had to reinstall junction though, not sure if it was updated or not but after a reinstall it shows Firefox and opens links as expected.

Gonna close the issue I think, seems to work nicely :)

**Comment by sonnyp** [comment]
I fixed it in 1.4.0 which was just made available.

> I use it a lot and it solves all my workflow problems

I'm glad to hear

You can tip if you want to support Junction https://ko-fi.com/sonnyp - even a small one helps.

Cheers!
