### ISSUE TITLE
Junction Popup - Window Placement 

### ISSUE THREAD

**Issue by sonicnkt** [sonnyp/Junction#60]
The Junction Popup window behaves like any normal window in mutter. So it is placed on the top left of the desktop if that is free or otherwise in free space on the desktop (i think). 

I am no gnome/mutter developer but would it be possible to create the window at the current cursor position? Sometime there is a lot of "mouse travel" involved to navigating to it which make this a bit cumbersome  (i know i can use the keyboard for junction). 
For example i have a nautilus window at the bottem right, double click a file and junction opens at the top left.

**Comment by sonnyp** [comment]
https://github.com/sonnyp/Junction/issues/35

If someone is motivated enough to make Junction inject a GNOME Shell extension, then it may be possible.

**Comment by sonicnkt** [comment]
Ah sorry i missed this!
