### ISSUE TITLE
Create backround layer behind Junction main window

### ISSUE THREAD

**Issue by VodnikAngus** [sonnyp/Junction#64]
Hi, I had two big issues and I found that they were posted and closed as #10 and #35. I have an idea how to fix both of those in the same time.
This could be accomplished by creating an invisible or translucent layer behind the main junction app. Clicking on this background layer would close junction app when you don't want to open any links and It could be used to locate pointer and add the main interface of the app behind cursor.
Implemented as is Junction is very irritating to use since to close it I need to press `esc` key and to open any link I have to move my cursor around the display.
I did set global gnome window centering but that is not a real solution.

**Comment by sonnyp** [comment]
Please comment on the issues next time.

Your suggestion is not reasonable, it's too hackish and will break many things such as application overview in GNOME Shell.

If you want to help, please help with the protocols, APIs, and implementations required for this.
