### ISSUE TITLE
Permission question

### ISSUE THREAD

**Issue by prog-amateur2** [sonnyp/Junction#69]
Hello, already thank you very much for this very useful application which (as far as I'm concerned) fills a gap in the GNOME interface. 

I would like to know if the permissions could be improved, i.e. less intrusive? It says: 
- arbitrary permissions (very dangerous in terms of computer security)
- full read access to the filesystem (also a risk, but I think a little less serious because it is only read access). 
![Screenshot from 2022-04-08 00-12-41](https://user-images.githubusercontent.com/60101083/162328581-189de814-b8fc-4b4e-b3d9-9d139f9b2d92.png)

## Question
Would it be possible to stop these two warnings by restricting the permissions of this tool? 

Thanks again for your kind help.

**Comment by sonnyp** [comment]
Hello, 

Unfortunally, because of what Junction does and how it must be done for a 3rd party application, there is no way to get around these warnings.

Howver Junction may get upstreamed as a native GNOME feature in the future.
