### ISSUE TITLE
View all does not have any icon.

### ISSUE THREAD

**Issue by abinlatheef** [sonnyp/Junction#71]
![image](https://user-images.githubusercontent.com/63762448/163837733-8240b215-437f-4de7-bd6d-23b2938704da.png)

Is there any way to configure the display icon theme?

**Comment by sonnyp** [comment]
How did you install Junction and which operating system?

**Comment by abinlatheef** [comment]
I am on Arch Linux and installed junction from the AUR iirc.

**Comment by sonnyp** [comment]
Is this still an issue?

Do you use a custom icon theme?

`view-more-horizontal-symbolic` is part of Adwaita Icon Theme
