### ISSUE TITLE
remove / add applications per mimetype

### ISSUE THREAD

**Issue by theotheroracle** [sonnyp/Junction#72]
for each mimetype, it would be nice to be able to remove and add applications from the list

**Comment by sonnyp** [comment]
What problem does it solve?

FYI you can use [xdg-mime](https://linux.die.net/man/1/xdg-mime) to do this system-wide

**Comment by theotheroracle** [comment]
its quite cumbersome to search for it everytime and maybe junction could provide a ui to do it with xdg-mime if thats the optimal solution ?

**Comment by sonnyp** [comment]
> its quite cumbersome to search for it everytime a

To search for what? Please describe the user problem you would like to solve in details?

The point of Junction is to let the user choose the application to open the resource with – so I don't see why you would want to remove options ? It's not obvious to me.

> maybe junction could provide a ui to do it with xdg-mime if thats the optimal solution ?

Then it's best left for a separate app

**Comment by theotheroracle** [comment]
the purpose would be for applications that i specifically dont want to show up in junction but still be registered for that mimetype, like a browser i dont use very often and i dont want to crowd junction with

**Comment by sonnyp** [comment]
No, I'm not adding manual and tedious apps management for something that's not a usability issue and can be solved with xdg-mime

See also https://github.com/sonnyp/Junction/issues/80
