### ISSUE TITLE
Support for application actions

### ISSUE THREAD

**Issue by jle64** [sonnyp/Junction#76]
It would be nice if support for [application actions](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#extra-actions) (aka jumplists) could be added, so that if a desktop entry defines additional actions we could use them to open files/links.

For example this would allow to open stuff in a browser private window or new window.

**Comment by sonnyp** [comment]
It's already supported - for now the UI is right click on the app icon 

See https://github.com/sonnyp/Junction/pull/46

**Comment by sonnyp** [comment]
> It doesn't seem to work on my system though, nothing happens on right click despite actions existing in the desktop file.

For which app? What does the desktop file look like ?

**Comment by jle64** [comment]
Looking at the desktop files I found the issue. The problem is not with junction its with the desktop files of some app not including "%u" in their action lines, hence while they didn't show up and I assumed it was not supported. When I edit them to add %u on the line they show up in junction and it works.

Anyway sorry and thanks for your time (and for junction).

**Comment by sonnyp** [comment]
Out of curiosity – can you share the apps ?

**Comment by jle64** [comment]
Well there was only "ungoogled chromium" which misses %u upstream at least in the flathub flatpak, the other one was firefox but it was only an issue due to my own changes to the file :)

**Comment by sonnyp** [comment]
Thanks


Epihany was mising it as well - I fixed it in https://gitlab.gnome.org/GNOME/epiphany/-/merge_requests/1049

For "ungoogled chromium" - could you fix or report the problem upstream?

**Comment by jle64** [comment]
And they fixed it.

**Comment by sonnyp** [comment]
Thanks for helping everyone  \o/
