### ISSUE TITLE
Options aren't displaying in plasma desktop

### ISSUE THREAD

**Issue by ayr-ton** [sonnyp/Junction#77]
I'm using KDE Plasma 5.24.5 and opening links works as expected, I have Junction as my default browser. It displays all the browsers I have installed once I try to open a link.

The issue is when I open Junction for customization. It keeps saying "Set junction as default browser" so I can't remove or change existing browsers options like in Gnome:
![image](https://user-images.githubusercontent.com/1090517/170169822-da3e19bd-75e4-4723-9634-e8ea2f65918b.png)

I've installed it via Flatpak.

**Comment by sonnyp** [comment]
I don't understand what the problem is.

Are you asking where to change the default browser in KDE?

https://wiki.debian.org/DefaultWebBrowser#KDE

**Comment by ayr-ton** [comment]
@sonnyp No. The default browser is Junction.
But when I open Junction it keeps saying I need to set it as the default browser and doesn't display the customization options.

When I try to open a new link, it displays all browsers I have installed so it kinda works, but I can't make any customization, this is the bug.

**Comment by sonnyp** [comment]
The UI is not ideal but is working as expected. There is no bug here.

**Comment by ayr-ton** [comment]
It's a feature, then.

**Comment by sonnyp** [comment]
Feel free to submit a PR or a mockup
