### ISSUE TITLE
Brave flatpak don't appear

### ISSUE THREAD

**Issue by BirdInFire** [sonnyp/Junction#78]
Hello i have a problem i have brave flatpak (with custom .desktop into ~/.local/share.

But this browser don't appear into junction (it appear into the gnome settings to be the default browser) but not into junction (if i click on the "..." brave flatpak is in the list.

Can you add a way to let us select default app for a specific protocol (for instance http/https), to add it into the default choice manually

**Comment by sonnyp** [comment]
What is the full path of the `.desktop` file and its content?

How many browsers do you have?

**Comment by BirdInFire** [comment]
> What is the full path of the `.desktop` file and its content?
> 
> How many browsers do you have?

the .desktop is nearly identical i only have added : "--ozone-platform=wayland" between com.brave.broser and %U

**Comment by sonnyp** [comment]
If you want help, please answer the questions.

> What is the full path of the .desktop file and its content?

**Comment by BirdInFire** [comment]
~/.local/share/applications/com.brave.Browser.desktop

`[Desktop Entry]
Version=1.0
Name=Brave Web Browser
GenericName=Web Browser
Comment=Access the Internet
Exec=/usr/bin/flatpak run com.brave.Browser --ozone-platform=wayland %U
StartupNotify=true
Terminal=false
Icon=brave-browser
Type=Application
Categories=Network;WebBrowser;
Actions=new-window;new-private-window;

[Desktop Action new-window]
Name=New Window
Exec=/usr/bin/flatpak run com.brave.Browser --ozone-platform=wayland

[Desktop Action new-private-window]
Name=New Incognito Window
Exec=/usr/bin/flatpak run com.brave.Browser --incognito --ozone-platform=wayland
MimeType=x-scheme-handler/unknown;x-scheme-handler/about;application/pdf;application/rdf+xml;application/rss+xml;application/xhtml+xml;application/xhtml_xml;application/xml;image/gif;image/jpeg;image/png;image/webp;text/html;text/xml;x-scheme-handler/http;x-scheme-handler/https;x-scheme-handler/ipfs;x-scheme-handler/ipns;`

**Comment by sonnyp** [comment]
I create exactly the same file and it appears in Junction, albeit with a broken icon

![Screenshot from 2022-07-31 21-19-24](https://user-images.githubusercontent.com/19673/182041820-39cec375-ca0f-4873-8e3f-3be8106a4d8f.png)

But now I realized you said it was working so I'm not really sure what this issue is about

> if i click on the "..." brave flatpak is in the list.

Use it once and it will appear in the main Junction list next time

https://github.com/sonnyp/Junction/issues/81 will fix this properly by removing the `...` list

**Comment by sonnyp** [comment]
I see.

It never appears in the main list? Even after having selected it once?

Please share the content of `System` panel in the Junction about dialog.
