### ISSUE TITLE
Host installation of Tor Browser Launcher not listed under Browsers

### ISSUE THREAD

**Issue by de-abreu** [sonnyp/Junction#8]
Hi.

I've the Tor Browser Laucher launcher installed from Manjaro's official repositories. It's executable is at `/usr/local/bin/torbrowser-launcher` and its desktop file lies at `/home/user/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/start-tor-browser.desktop`

Could it be listed as a browser option at Junction?

**Comment by sonnyp** [comment]
Hello,

Junction and operating system versions please.
