### ISSUE TITLE
Firefox not showing among browser options

### ISSUE THREAD

**Issue by Sriramgireesh** [sonnyp/Junction#86]
When I click a link,  browsers such as Chrome, Edge, Brave and Vivaldi show up but Firefox does not. Is there any way to make Firefox appear among the top options?

**Comment by sonnyp** [comment]
Open once with Firefox from the "View all" option, next time Firefox should appear in the main list of option.

**Comment by Sriramgireesh** [comment]
Hi, I have  done that but Firefox still does not show up.

**Comment by sonnyp** [comment]
How did you install Junction?

How did you install Firefox?

What is your operating system / version ?

**Comment by Sriramgireesh** [comment]
I installed Firefox and Junction Flathubs via Discover. My operating system is KDE Neon 5.25

**Comment by istdochegal11** [comment]
I have the same issue with the flatpak versions of Firefox and Junction.
And I can not reproduce this with the git verson.

**Comment by lostfictions** [comment]
I've noticed something similar on SteamOS/Arch, with Firefox, Chromium and Junction all installed via Flatpak.

Chromium works fine, while Firefox.... sort of shows up, but it can't find the icon, and clicking it goes to the Gnome Software Center (or Discover on KDE Plasma) page for Firefox rather than opening it.

![Screenshot](https://user-images.githubusercontent.com/567041/193377359-fed29d85-e5fd-485d-a8db-38c177df61b7.png)

**Comment by sonnyp** [comment]
@lostfictions looks like a separate issue – possibly same as https://github.com/sonnyp/Junction/issues/93

**Comment by sonnyp** [comment]
@Sriramgireesh @istdochegal11 can you confirm with this beta version that it's now working properly?

```
flatpak install --user https://dl.flathub.org/build-repo/114055/re.sonny.Junction.flatpakref
flatpak run re.sonny.Junction//test https://example.com
```

**Comment by sonnyp** [comment]
@lostfictions can you try again with the beta version and if it still doesn't work – please open a new issue.

**Comment by sonnyp** [comment]
I can't reproduce with the following steps:

1. Install KDE Neon 5.26 in a VM
2. `flatpak install firefox`
3. `flatpak install junction`
4. `flatpak run re.sonny.Junction`

Both Firefox system and Firefox flatpak show.

However I've noticed this happened before on my Fedora. Somehow it doesn't anymore.

Trying updated your system to KDE Neon 5.26 and Junction to 1.6 (soon on Flathub)

If it persists, please comment and share the details of Junction -> About -> System
