### ISSUE TITLE
Open Links in different Firefox Profiles?

### ISSUE THREAD

**Issue by ghost** [sonnyp/Junction#9]
Hello, I use 4 different Firefox profiles to separate work from personal from shopping etc. Would be great if I could somehow add those profiles to the selection screen of junction and select the opening of certain links in certain firefox profiles.

**Comment by ocosta** [comment]
Sorry to bring this back from the dead, but for some (probably stupid) reason this is not working for me.

```
❯ ls -l .local/share/applications/firefox-work.desktop 
-rw-r--r--. 1 costa costa 400 out 30 16:41 .local/share/applications/firefox-work.desktop

~ 
❯ cat .local/share/applications/firefox-work.desktop
[Desktop Entry]
Name=Firefox Work
Comment=Firefox with work profile
Exec=firefox -P Trabalho --class=firefox-work %u
Icon=tecgraf-logo.png
Terminal=false
Type=Application
StartupNotify=true
StartupWMClass=firefox-work
#Categories=Network;WebBrowser;
MimeType=text/html;text/xml;application/xhtml+xml;application/vnd.mozilla.xul+xml;text/mml;x-scheme-handler/http;x-scheme-handler/https;
Hidden=false

~ 
❯ update-desktop-database ~/.local/share/applications/

```

However, Junction still only shows one Firefox icon and one Chromium icon. The "Firefox Work" app appears just fine as a GNOME app, with the custom icon, and it runs just fine.

@sonnyp can you spot what I'm doing wrong? I'm running Fedora 43.
