### ISSUE TITLE
Centre Junction window on screen

### ISSUE THREAD

**Issue by mjog** [sonnyp/Junction#90]
For me, the Junction window shows up in the top left hand corner of the screen, which for me is a bit surprising since I am used to the gnome-shell switcher (which Junction looks a lot like) showing up in the centre of the screen instead.

It would be great if Junction also appeared centred to for consistency.

PS thanks for this app, I've been wanting something like this for ages! <3

**Comment by omnicortex** [comment]
I would like to add instruction for Cinnamon in the README under "Make Junction appear in the center of the screen". 

Go to __System Settings__ > __Windows__ > __Behavior__, and look for the "Location of newly opened windows" option. There are four choices: Automatic, Cursor, Manual, and Center.

Or using terminal:
```
gsettings set org.cinnamon.muffin placement-mode 'center'
```
