### ISSUE TITLE
Browser doesn't open

### ISSUE THREAD

**Issue by haeckle** [sonnyp/Junction#92]
Trying to open an URL with Firefox or ungoogled Chromium _sometimes_ doesn't succeed. When invoking Junction via commandline an error is displayed:
`Error: no DISPLAY environment variable specified`
Also trying to set the variable via `flatpak run env="DISPLAY=:0" re.sonny.Junction <URL>` doesn't work.
Nevertheless opening with GNOME Web (Epiphany) always works.

I'm on Fedora Silverblue with system-provided Firefox. Junction, Epiphany and ungoogled Chromium are installed via Flathub.

**Comment by sonnyp** [comment]
I'm sorry but I don't see how this is an issue with Junction. Most likely related to your shell / env.
