### ISSUE TITLE
Remove app from sugesstions

### ISSUE THREAD

**Issue by G-R-A-F-F** [sonnyp/Junction#95]
Hello,

Please explain the process of removing an app from the suggestion list. 
I picked Flash Player to open pdf by accident, now it is there as a first option all the time.

![image](https://user-images.githubusercontent.com/15918798/197366490-0c0818fd-fbb1-4205-ab4e-9704923c8764.png)

Thank you

**Comment by G-R-A-F-F** [comment]
Thanks. XFCE has that under Settings>Default Apllications>Other.

**Comment by sonnyp** [comment]
https://github.com/sonnyp/Junction/issues/72
