### ISSUE TITLE
Feature Request: Automatically pick a certain app based on the source app

### ISSUE THREAD

**Issue by stefanfoulis** [sonnyp/Junction#98]
_I'm not sure if this is even possible with the given apis. I skimmed open and closed tickets and couldn't find one that matches this. I hope I didn't miss one._

I use Junction to pick whether I want to open a link in my "Personal" browser or my "Work" browser. Some source applications are always for work or always for personal. For example if I click on a link in Slack, I'd always want it to open in my work browser.

Similarly (and probably more realistic based on available apis) would be to be able to open certain urls in certain browsers. For example open all youtube urls in the personal browser. (this part should probably be a separate ticket)

**Comment by sonnyp** [comment]
> Similarly (and probably more realistic based on available apis) would be to be able to open certain urls in certain browsers. For example open all youtube urls in the personal browser. (this part should probably be a separate ticket)

https://github.com/sonnyp/Junction/issues/5

For source app stuff - yeah it's not currently possible. We can re-open this if it does become doable.
